### ISSUE TITLE
Generate package feeds

### ISSUE THREAD

**Issue by wfailla** [carosio/kellner#2]
It would be nice if the Kellner would be able to generate a package feed configuration.
That can be copy pasted or wgeted or curled in to the system.

The package feed should look like this:

```
src/gz <name> <url>
src/gz <name> <url>
...
```

The repository names must be unique.
Each directory containing packages served by the Kellner needs to be one separate line in the feeds configuration.

**Comment by mgumz** [comment]
implemented via c7e8947

**Comment by wfailla** [comment]
Works as expected.
I was able to wget the configuration directly from kellner.
